package com.cy.store.mapper;

import com.cy.store.entity.Cart;

import java.util.Date;
import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    Cart selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sat Jul 16 09:20:03 CST 2022
     */
    int updateByPrimaryKey(Cart record);

    /**
     * 项购物车添加数据
     * @param cart
     * @return
     */
    Integer insertCart(Cart cart);

    /**
     * 如果商品在购物车存在，则增加数量
     * @param num
     * @param cid
     * @return
     */
    Integer updateCartByNum(Integer num, Integer cid, String modifiedUser, Date modifiedTime);

    /**
     * 查询商品是否存在
     * @param pid
     * @param uid
     * @return
     */
    Cart queryCartByCidAndPid(Integer pid,Integer uid);

    /**
     * 根据用户id查询购物车里的商品
     * @param uid
     * @return
     */
    List<Cart> findCartOnProductByUid(Integer uid);

    /**
     * 根据cid查询购物车商品是否存在
     * @param cid
     * @return
     */
    Cart queryCartByCid(Integer cid);

    /**
     * 根据传递的cid集合查询相关的信息
     * @param cid
     * @return
     */
    List<Cart> findCartByCidList(String[] cid);
}