package com.cy.store.mapper;

import com.cy.store.entity.District;

import java.util.List;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    District selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Thu Jul 14 15:22:33 CST 2022
     */
    int updateByPrimaryKey(District record);

    /**
     * 根据父代号查询
     * @param parent
     * @return
     */
    List<District> queryDistrictByParent(String parent);

    /**
     * 根据代号查询区地址
     * @param code
     * @return
     */
    String queryNameByCode(String code);
}