package com.cy.store.mapper;

import com.cy.store.entity.User;

import java.util.Date;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Jul 14 10:48:14 CST 2022
     */
    int updateByPrimaryKey(User record);

    Integer insertUser(User user);

    User fingByUserName(String username);

    User querUserByUid(Integer uid);

    Integer updatePasswordByUid(Integer uid, String password, String modifiedUser, Date modifiedTime);

    Integer updateUserById(User user);

    Integer updateAvatarByUid(Integer uid,String avatar,String modifiedUser,Date modifiedTime);
}