package com.cy.store.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.oid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.uid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_name
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_phone
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_province
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_city
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_area
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_address
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String recvAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_price
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Long totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.created_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.created_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.modified_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.modified_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.oid
     *
     * @return the value of t_order.oid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.oid
     *
     * @param oid the value for t_order.oid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.uid
     *
     * @return the value of t_order.uid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.uid
     *
     * @param uid the value for t_order.uid
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_name
     *
     * @return the value of t_order.recv_name
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvName() {
        return recvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_name
     *
     * @param recvName the value for t_order.recv_name
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvName(String recvName) {
        this.recvName = recvName == null ? null : recvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_phone
     *
     * @return the value of t_order.recv_phone
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvPhone() {
        return recvPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_phone
     *
     * @param recvPhone the value for t_order.recv_phone
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvPhone(String recvPhone) {
        this.recvPhone = recvPhone == null ? null : recvPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_province
     *
     * @return the value of t_order.recv_province
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvProvince() {
        return recvProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_province
     *
     * @param recvProvince the value for t_order.recv_province
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvProvince(String recvProvince) {
        this.recvProvince = recvProvince == null ? null : recvProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_city
     *
     * @return the value of t_order.recv_city
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvCity() {
        return recvCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_city
     *
     * @param recvCity the value for t_order.recv_city
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvCity(String recvCity) {
        this.recvCity = recvCity == null ? null : recvCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_area
     *
     * @return the value of t_order.recv_area
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvArea() {
        return recvArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_area
     *
     * @param recvArea the value for t_order.recv_area
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvArea(String recvArea) {
        this.recvArea = recvArea == null ? null : recvArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_address
     *
     * @return the value of t_order.recv_address
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getRecvAddress() {
        return recvAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_address
     *
     * @param recvAddress the value for t_order.recv_address
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setRecvAddress(String recvAddress) {
        this.recvAddress = recvAddress == null ? null : recvAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_price
     *
     * @return the value of t_order.total_price
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_price
     *
     * @param totalPrice the value for t_order.total_price
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_time
     *
     * @return the value of t_order.order_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_time
     *
     * @param orderTime the value for t_order.order_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.created_user
     *
     * @return the value of t_order.created_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.created_user
     *
     * @param createdUser the value for t_order.created_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.created_time
     *
     * @return the value of t_order.created_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.created_time
     *
     * @param createdTime the value for t_order.created_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.modified_user
     *
     * @return the value of t_order.modified_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.modified_user
     *
     * @param modifiedUser the value for t_order.modified_user
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.modified_time
     *
     * @return the value of t_order.modified_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.modified_time
     *
     * @param modifiedTime the value for t_order.modified_time
     *
     * @mbggenerated Sat Jul 23 13:10:07 CST 2022
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        return "Order{" +
                "oid=" + oid +
                ", uid=" + uid +
                ", recvName='" + recvName + '\'' +
                ", recvPhone='" + recvPhone + '\'' +
                ", recvProvince='" + recvProvince + '\'' +
                ", recvCity='" + recvCity + '\'' +
                ", recvArea='" + recvArea + '\'' +
                ", recvAddress='" + recvAddress + '\'' +
                ", totalPrice=" + totalPrice +
                ", status=" + status +
                ", orderTime=" + orderTime +
                ", payTime=" + payTime +
                ", createdUser='" + createdUser + '\'' +
                ", createdTime=" + createdTime +
                ", modifiedUser='" + modifiedUser + '\'' +
                ", modifiedTime=" + modifiedTime +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(oid, order.oid) &&
                Objects.equals(uid, order.uid) &&
                Objects.equals(recvName, order.recvName) &&
                Objects.equals(recvPhone, order.recvPhone) &&
                Objects.equals(recvProvince, order.recvProvince) &&
                Objects.equals(recvCity, order.recvCity) &&
                Objects.equals(recvArea, order.recvArea) &&
                Objects.equals(recvAddress, order.recvAddress) &&
                Objects.equals(totalPrice, order.totalPrice) &&
                Objects.equals(status, order.status) &&
                Objects.equals(orderTime, order.orderTime) &&
                Objects.equals(payTime, order.payTime) &&
                Objects.equals(createdUser, order.createdUser) &&
                Objects.equals(createdTime, order.createdTime) &&
                Objects.equals(modifiedUser, order.modifiedUser) &&
                Objects.equals(modifiedTime, order.modifiedTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(oid, uid, recvName, recvPhone, recvProvince, recvCity, recvArea, recvAddress, totalPrice, status, orderTime, payTime, createdUser, createdTime, modifiedUser, modifiedTime);
    }
}