package com.cy.store.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.category_id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.item_type
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.title
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sell_point
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.num
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.status
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.priority
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.created_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.modified_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.created_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.modified_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    private String modifiedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.category_id
     *
     * @return the value of t_product.category_id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.category_id
     *
     * @param categoryId the value for t_product.category_id
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.item_type
     *
     * @return the value of t_product.item_type
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.item_type
     *
     * @param itemType the value for t_product.item_type
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.title
     *
     * @return the value of t_product.title
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.title
     *
     * @param title the value for t_product.title
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sell_point
     *
     * @return the value of t_product.sell_point
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sell_point
     *
     * @param sellPoint the value for t_product.sell_point
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.num
     *
     * @return the value of t_product.num
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.num
     *
     * @param num the value for t_product.num
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image
     *
     * @return the value of t_product.image
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image
     *
     * @param image the value for t_product.image
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.status
     *
     * @return the value of t_product.status
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.status
     *
     * @param status the value for t_product.status
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.priority
     *
     * @return the value of t_product.priority
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.priority
     *
     * @param priority the value for t_product.priority
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.created_time
     *
     * @return the value of t_product.created_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.created_time
     *
     * @param createdTime the value for t_product.created_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.modified_time
     *
     * @return the value of t_product.modified_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.modified_time
     *
     * @param modifiedTime the value for t_product.modified_time
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.created_user
     *
     * @return the value of t_product.created_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.created_user
     *
     * @param createdUser the value for t_product.created_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.modified_user
     *
     * @return the value of t_product.modified_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.modified_user
     *
     * @param modifiedUser the value for t_product.modified_user
     *
     * @mbggenerated Fri Jul 15 16:19:44 CST 2022
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", categoryId=" + categoryId +
                ", itemType='" + itemType + '\'' +
                ", title='" + title + '\'' +
                ", sellPoint='" + sellPoint + '\'' +
                ", price=" + price +
                ", num=" + num +
                ", image='" + image + '\'' +
                ", status=" + status +
                ", priority=" + priority +
                ", createdTime=" + createdTime +
                ", modifiedTime=" + modifiedTime +
                ", createdUser='" + createdUser + '\'' +
                ", modifiedUser='" + modifiedUser + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(id, product.id) &&
                Objects.equals(categoryId, product.categoryId) &&
                Objects.equals(itemType, product.itemType) &&
                Objects.equals(title, product.title) &&
                Objects.equals(sellPoint, product.sellPoint) &&
                Objects.equals(price, product.price) &&
                Objects.equals(num, product.num) &&
                Objects.equals(image, product.image) &&
                Objects.equals(status, product.status) &&
                Objects.equals(priority, product.priority) &&
                Objects.equals(createdTime, product.createdTime) &&
                Objects.equals(modifiedTime, product.modifiedTime) &&
                Objects.equals(createdUser, product.createdUser) &&
                Objects.equals(modifiedUser, product.modifiedUser);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, categoryId, itemType, title, sellPoint, price, num, image, status, priority, createdTime, modifiedTime, createdUser, modifiedUser);
    }
}